---
- name: Install dependencies
  apt:
    name:
    - apt-transport-https
    - gpg
    - software-properties-common
  when: ansible_facts.services["grafana-server.service"] is not defined

- name: Fetch GPG key for Grafana
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  when: ansible_facts.services["grafana-server.service"] is not defined

- name: Add Grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana
  when: ansible_facts.services["grafana-server.service"] is not defined

- name: Install Grafana
  apt:
    name: grafana
  when: ansible_facts.services["grafana-server.service"] is not defined
  notify:
  - Enable Grafana service

- name: Setup Grafana
  copy:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
    backup: yes
    group: grafana
    mode: '640'
  when: ansible_facts.services["grafana-server.service"] is not defined

- name: Allow port connection
  ufw:
    rule: allow
    port: http
    proto: tcp
  when: ansible_facts.services["grafana-server.service"] is not defined
  notify:
  - Reload UFW

- name: Allow Grafana to bind to port 80
  command: setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server
  when: ansible_facts.services["grafana-server.service"] is not defined
  notify:
  - Restart Grafana
