---
- name: Install Prometheus and Node Exporter
  apt:
    name:
    - prometheus
    - prometheus-node-exporter
    install_recommends: yes
    state: latest
  when: ansible_facts.services["prometheus.service"] is not defined

- name: Setup Prometheus
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    backup: yes
  when: ansible_facts.services["prometheus.service"] is not defined
  notify:
  - Restart Prometheus

- name: Setup Prometheus node-exporter
  copy:
    src: prometheus-node-exporter
    dest: /etc/default/prometheus-node-exporter
    backup: yes
  when: ansible_facts.services["prometheus.service"] is not defined
  notify:
  - Restart Prometheus node-exporter

- name: Allow port connection
  ufw:
    rule: limit
    port: '9090'
    proto: tcp
  when: ansible_facts.services["prometheus.service"] is not defined
  notify:
  - Reload UFW
