---
all:
  hosts:
    raspberrypi.local:
      ansible_connection: ssh
      ansible_user: pi
      ansible_password: raspberry
      ansible_python_interpreter: /usr/bin/python3
      app:
        path: /opt/pi-sensors
        port: 3000
