---
- name: Configure hardware interfaces
  command: >
    raspi-config nonint do_i2c 0
    raspi-config nonint do_spi 0
    raspi-config nonint set_config_var enable_uart 1 /boot/config.txt
    raspi-config nonint do_serial 1

- name: Update boot configuration
  lineinfile:
    path: /boot/config.txt
    line: "dtoverlay=pi3-miniuart-bt"

- name: Install dependencies
  apt:
    name:
    - python3-numpy
    - python3-pil
    - python3-setuptools
    - python3-smbus
    install_recommends: no
    state: latest

- name: Install Python packages
  pip:
    name: enviroplus
