from instruments.bme280 import BME280
from instruments.cpu import CPU
from instruments.disk import Disk
from instruments.enviro import Enviro
from instruments.hardware import Hardware
from instruments.ltr559 import LTR559
from instruments.memory import Memory
from instruments.network import Network
from instruments.sensors import Sensors
